# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3818bcfa502af8c9cff658cff5f750b5f686341a7bfb388516c7a451aff5739228e9003ab54529175834ab69219f869b9187d9b96210031a28c51e57fcde2376

test:
  secret_key_base: 74790c8b25aceb52843bcdd4332db2b3d5670742459d0649033271c302a8802dd56a9c6ad25498540b0eaf8e8bf230a0c1af32572f8d5c1e6be7b7492dc82785

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
